### PR TITLE
Including tpl changes

### PR DESCRIPTION
**Pull request by DandyDeveloper**
Signed-off-by: Aaron Layfield <aaron.layfield@gmail.com>

### CODE REVIEW

**Review by sastorsl — CHANGES_REQUESTED** [review]
Replacing with `tpl` works as expected - of course as long as `opensearch.yml` config is added to `values.yaml` as a string - as you point out.

I like that you add a `log4j2.properties` example.
However, I think it should be commented out, and have real values.
Perhaps the comment also need to explicitly say that the whole file will be replaced?

**Comment by DandyDeveloper** [comment]
@sastorsl This was purely to show you it working. I'll update to actually fix it better with real out properties.

**Comment by DandyDeveloper** [comment]
@sastorsl Done. Take a look.

**Comment by sastorsl** [comment]
@DandyDeveloper great!

One more thing - there always is isn't it...

The default / demo config logs to console, which I think should be the default in the container world.
Somebody will perhaps run this directly and end up with a local file which can become quite large.

Should the log4j2 example either match the one in the default config, or be commented out in the example `values.yaml`

This is the default:

```
status = error
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n
rootLogger.level = info
rootLogger.appenderRef.console.ref = console
```

Is it this one perhaps?
https://github.com/opensearch-project/OpenSearch/blob/main/qa/os/src/test/resources/log4j2-test.properties

**Comment by sastorsl** [comment]
@DandyDeveloper how to you want to proceed?
I can incorporate your changes in a commit of my own, or merge your PR.
I haven't done that (merge PR into my private fork) before so hopefully I won't mess it up.

Give me your thoughts on it.

**Comment by DandyDeveloper** [comment]
@sastorsl The latter as well as including the above recommendations seem like a good way forward to me!

**Comment by DandyDeveloper** [comment]
But you should be able to merge my change here, then adjust your branch. That'll automatically update whatever PR has been created against this branch.

**Pull request merged**
